name: Auto-Tag Only on Version Change

on:
  push:
    branches:
      - main

jobs:
  version-check:
    name: Check version change and tag
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # needed to compare to previous commit

      - name: Get current version from build.gradle
        id: version
        run: |
          version=$(grep "^version" build.gradle | cut -d"'" -f2)
          echo "Detected version: $version"
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Check if tag already exists
        id: tag_exists
        run: |
          git fetch --tags
          if git rev-parse "v${{ steps.version.outputs.version }}" >/dev/null 2>&1; then
            echo "Tag already exists."
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "Tag does not exist."
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Run tests before tagging
        run: ./gradlew test

      - name: Tag and push if new version
        if: steps.tag_exists.outputs.exists == 'false'
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git tag v${{ steps.version.outputs.version }}
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git v${{ steps.version.outputs.version }}
