name: Publish to Maven Central

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  publish:
    name: Publish Plugin
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21
          cache: gradle

      - name: Extract version from build.gradle
        id: version
        run: echo "version=$(./gradlew -q properties | grep '^version:' | awk '{print $2}')" >> $GITHUB_OUTPUT

      - name: Import GPG Key
        run: |
          echo "$GPG_PRIVATE_KEY" | gpg --batch --import
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}

      - name: Build and sign artifacts
        run: ./gradlew clean build generatePomFileForMavenJavaPublication publishToMavenLocal signMavenJavaPublication

      - name: Package bundle for Sonatype Central
        run: |
          mkdir bundle
          cp build/libs/*.jar bundle/
          cp build/publications/mavenJava/*.pom bundle/
          cp build/libs/*.jar.asc bundle/ || true
          cp build/publications/mavenJava/*.pom.asc bundle/ || true
          zip -r central-bundle.zip bundle

      - name: Upload bundle to Central Publisher Portal
        id: upload
        run: |
          response=$(curl -s -X POST \
            -H "Authorization: Bearer $SONATYPE_TOKEN" \
            -F bundle=@central-bundle.zip \
            https://central.sonatype.com/api/v1/publisher/upload)
          
          echo "$response"
          echo "deployment_id=$(echo $response | jq -r '.deploymentId')" >> $GITHUB_OUTPUT
        env:
          SONATYPE_TOKEN: ${{ secrets.SONATYPE_TOKEN }}

      - name: Poll validation & publish
        run: |
          echo "Waiting for validation..."
          for i in {1..10}; do
            sleep 15
            status=$(curl -s -X POST \
              -H "Authorization: Bearer $SONATYPE_TOKEN" \
              "https://central.sonatype.com/api/v1/publisher/status?id=${{ steps.upload.outputs.deployment_id }}" \
              | jq -r '.status')
          
            echo "Status: $status"
          
            if [[ "$status" == "VALIDATED" ]]; then
              echo "Publishing..."
              curl -X POST \
                -H "Authorization: Bearer $SONATYPE_TOKEN" \
                "https://central.sonatype.com/api/v1/publisher/deployment/${{ steps.upload.outputs.deployment_id }}"
              exit 0
            elif [[ "$status" == "FAILED" ]]; then
              echo "Validation failed"
              exit 1
            fi
          done
          
          echo "Timeout waiting for validation"
          exit 1
        env:
          SONATYPE_TOKEN: ${{ secrets.SONATYPE_TOKEN }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.version.outputs.version }}
          name: Release v${{ steps.version.outputs.version }}
          body: |
            Spring Boot Scaffolder plugin v${{ steps.version.outputs.version }} is now live!
            - Published to Gradle Plugin Portal
            - Published to Maven Central
            - Includes latest features and improvements
          files: build/libs/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.PUB_GITHUB_TOKEN }}
