name: 🚀 Publish to Plugin Portal & Maven Central

on:
  push:
    tags:
      - 'v*.*.*' # Exemple : v1.0.2

jobs:
  publish:
    name: Publish Plugin
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21
          cache: gradle

      - name: Extract version from build.gradle
        id: version
        run: echo "version=$(./gradlew -q properties | grep '^version:' | awk '{print $2}')" >> $GITHUB_OUTPUT

      - name: Build project
        run: ./gradlew clean build

      - name: Import GPG key for signing
        run: |
          echo "$SIGNING_KEY" | gpg --batch --import
        env:
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}

      - name: Publish to Gradle Plugin Portal & Maven Central
        run: ./gradlew publishPlugins publishToSonatype closeAndReleaseSonatypeStagingRepository --stacktrace
        env:
          ORG_GRADLE_PROJECT_gradle.publish.key: ${{ secrets.GRADLE_PUBLISH_KEY }}
          ORG_GRADLE_PROJECT_gradle.publish.secret: ${{ secrets.GRADLE_PUBLISH_SECRET }}
          ORG_GRADLE_PROJECT_ossrhUsername: ${{ secrets.OSSRH_USERNAME }}
          ORG_GRADLE_PROJECT_ossrhPassword: ${{ secrets.OSSRH_PASSWORD }}
          ORG_GRADLE_PROJECT_signing.keyId: ${{ secrets.SIGNING_KEY_ID }}
          ORG_GRADLE_PROJECT_signing.password: ${{ secrets.SIGNING_PASSWORD }}
          ORG_GRADLE_PROJECT_signing.secretKeyRingFile: ${{ github.workspace }}/secring.gpg

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.version.outputs.version }}
          name: Release v${{ steps.version.outputs.version }}
          body: |
            Spring Boot Scaffolder plugin v${{ steps.version.outputs.version }} is now live!
            - Published to Gradle Plugin Portal
            - Published to Maven Central
            - Includes latest features and improvements
          files: build/libs/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.PUB_GITHUB_TOKEN }}
